fix: fix front dockerfile (#7)
* fix: front docker test

* fix: fix dockerfile

* fix: fix docker final

* fix: fix lint

diff --git a/frontend/Dockerfile b/frontend/Dockerfile
--- a/frontend/Dockerfile
+++ b/frontend/Dockerfile
@@ -1,61 +1,69 @@
-# Multi-stage build
+FROM node:18-alpine AS base
 
-# 1단계 환경 설정 및 dependancy 설치
-FROM node:18-alpine AS deps
+# Install dependencies only when needed
+FROM base AS deps
+# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
 RUN apk add --no-cache libc6-compat
+WORKDIR /app
 
-# 명령어를 실행할 디렉터리 지정
-WORKDIR /usr/src/app
+# Install dependencies based on the preferred package manager
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 
-# Dependancy install을 위해 package.json, pnpm.lock 복사 
-COPY package.json pnpm.lock ./ 
 
-# Dependancy 설치
-RUN pnpm --frozen-lockfile 
-
-###########################################################
-
-# 2단계: next.js 빌드 단계
-FROM node:18-alpine AS builder
-
-# Docker를 build할때 개발 모드 구분용 환경 변수를 명시함
-ARG ENV_MODE
-
-# 명령어를 실행할 디렉터리 지정
-WORKDIR /usr/src/app
-
-# node_modules 등의 dependancy를 복사함.
-COPY --from=deps /usr/src/app/node_modules ./node_modules
+# Rebuild the source code only when needed
+FROM base AS builder
+WORKDIR /app
+COPY --from=deps /app/node_modules ./node_modules
 COPY . .
 
-# 구축 환경에 따라 env 변수를 다르게 가져가야 하는 경우 환경 변수를 이용해서 env를 구분해준다.
-COPY .env.$ENV_MODE ./.env.production
-RUN pnpm build
+# Next.js collects completely anonymous telemetry data about general usage.
+# Learn more here: https://nextjs.org/telemetry
+# Uncomment the following line in case you want to disable telemetry during the build.
+# ENV NEXT_TELEMETRY_DISABLED=1
 
-###########################################################
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
+RUN \
+  if [ -f yarn.lock ]; then yarn run build; \
+  elif [ -f package-lock.json ]; then npm run build; \
+  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run build; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 
-# 3단계:  next.js 실행 단계
-FROM node:18-alpine AS runner
+# Production image, copy all the files and run next
+FROM base AS runner
+WORKDIR /app
 
-# 명령어를 실행할 디렉터리 지정
-WORKDIR /usr/src/app
- 
-# container 환경에 시스템 사용자를 추가함
+ENV NODE_ENV=production
+# Uncomment the following line in case you want to disable telemetry during runtime.
+# ENV NEXT_TELEMETRY_DISABLED=1
+
 RUN addgroup --system --gid 1001 nodejs
 RUN adduser --system --uid 1001 nextjs
 
-# next.config.js에서 output을 standalone으로 설정하면 
-# 빌드에 필요한 최소한의 파일만 ./next/standalone로 출력이 된다.
-# standalone 결과물에는 public 폴더와 static 폴더 내용은 포함되지 않으므로, 따로 복사를 해준다.
-COPY --from=builder /usr/src/app/public ./public
-COPY --from=builder --chown=nextjs:nodejs /usr/src/app/.next/standalone ./
-COPY --from=builder --chown=nextjs:nodejs /usr/src/app/.next/static ./.next/static
- 
-# 빌드로 생성한 이미지의 수신 대기 포트를 3000으로 설정
+COPY --from=builder /app/public ./public
+
+# Set the correct permission for prerender cache
+RUN mkdir .next
+RUN chown nextjs:nodejs .next
+
+# Automatically leverage output traces to reduce image size
+# https://nextjs.org/docs/advanced-features/output-file-tracing
+COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
+COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
+
+USER nextjs
+
 EXPOSE 3000
 
-# node로 애플리케이션 실행
-CMD ["node", "server.js"] 
+ENV PORT=3000
 
-# standalone으로 나온 결과값은 node 자체적으로만 실행 가능
-# CMD ["npm", "start"]
+# server.js is created by next build from the standalone output
+# https://nextjs.org/docs/pages/api-reference/next-config-js/output
+ENV HOSTNAME="0.0.0.0"
+CMD ["node", "server.js"]
